### ISSUE TITLE
website_supplier

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/website#8]
Modul untuk menampilkan daftar/detail supplier

Dependensi:
- website_partner

Acceptance Criteria:
- [ ] Dibuat dengan mekanisme yang sama seperti **website_membership** atau **website_customer**
- [ ] Domain untuk data res.partner yang dimunculkan: (1) website_publish == True, (2) supplier == True
- [ ] https.routes awal == suppliers

**Comment by mikevhe18** [comment]
Link PR [#175](https://github.com/OCA/website/pull/175)
